<?php /* Smarty version 2.6.0, created on 2011-01-17 14:46:02
         compiled from index.tpl */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <!-- Generated by phpDocumaentor: <?php echo $this->_tpl_vars['date']; ?>
 -->
        <title><?php echo $this->_tpl_vars['title']; ?>
</title>
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>

    	<link rel="shortcut icon" href="http://crazytje.be/favicon.ico"></link>
    	<link rel="icon" href="http://crazytje.be/favicon.ico"></link>
        
    	<link rel="stylesheet" type="text/css" href="styles/phpdoc.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/jquery.treeview.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/jquery.layout.css"></link>
      <link rel="stylesheet" type="text/css" href="styles/aristo/jquery-ui.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/style.css"></link>
        

      <script type="text/javascript" src="scripts/jquery.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.cookie.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.query.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.jstree.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery-ui.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.layout.min.js" type="text/javascript"></script>
        
      <script type="text/javascript" src="scripts/common.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="loading-mask" style=""></div>
        <div id="loading">
            <div class="loading-indicator">
                <img alt="" src="images/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="middle"></img>
                Loading...
            </div>
        </div>
    
            <!-- ============ LEFT COLUMN (MENU) ============== -->
            <div class="ui-layout-west" id="left">

              <div id="searchbar" class="ui-layout-north">

                <input type="text" name="search" value="" id="search">

              </div>

              <div id='menu' class="ui-layout-center"></div>

            </div> <!-- end of layout-west -->
            
            <!-- ============ RIGHT COLUMN (CONTENT) ============== -->
            <div class="ui-layout-center" id="main">

              <div id="tabs">

                <ul>
                  <li><a href="#tabs-1">Home</a></li>
                </ul>

                <div id="tabs-1">

                  <?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "welcome.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?>

                </div>

              </div>

            </div> <!-- end of layout-center -->

            <!-- ============ FOOTER SECTION ============== -->
            <div id="footer" class="ui-layout-south">
              
                Copyright© 2010 <a href='http://www.carpe-hora.com' target='_blank'>Carpe Hora</a> 
                - Based on <a href='http://onigoetz.ch' target='_blank'>Onigoetz.ch</a> 
                  and <a href='http://evolve.crazytje.be' target='_blank'>Evolve </a>

            </div> <!-- end of layout-south -->

    </body>
<html>