<?php /* Smarty version 2.6.0, created on 2011-01-17 14:46:02
         compiled from blank.tpl */ ?>
<div class='page_content'>
<div align="center"><h1><?php echo $this->_tpl_vars['maintitle']; ?>
</h1></div>
<b>Welcome to <?php echo $this->_tpl_vars['package']; ?>
!</b><br />
<br />
This documentation was generated by <a href="<?php echo $this->_tpl_vars['phpdocwebsite']; ?>
">phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
</a><br />