<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <!-- Generated by phpDocumaentor: {$date} -->
        <title>{$title}</title>
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>

    	<link rel="shortcut icon" href="http://crazytje.be/favicon.ico"></link>
    	<link rel="icon" href="http://crazytje.be/favicon.ico"></link>
        
    	<link rel="stylesheet" type="text/css" href="styles/phpdoc.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/jquery.treeview.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/style.css"></link>
      <link rel="stylesheet" type="text/css" href="styles/aristo/jquery-ui.css"></link>
        

      <script type="text/javascript" src="scripts/jquery.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.cookie.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.query.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.jstree.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery-ui.js" type="text/javascript"></script>
      <script type="text/javascript" src="scripts/jquery.layout.js" type="text/javascript"></script>
        
      <script type="text/javascript" src="scripts/common.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="loading-mask" style=""></div>
        <div id="loading">
            <div class="loading-indicator">
                <img alt="" src="images/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="middle"></img>
                Loading...
            </div>
        </div>
    
        <table id='layout' style='width:100%;'>
            <tr>
                <!-- ============ LEFT COLUMN (MENU) ============== -->
                <td id='left' valign='top'><div id='menu'></div></td>
                <!-- ============ RIGHT COLUMN (CONTENT) ============== -->
                <td valign='top' width='100%'>
					<div id='tabs'>
						
						<ul>
							<li><a href="#tabs-1">Home</a></li>

						</ul>
						<div id="tabs-1">
							{include file="welcome.tpl"}
						</div>

						
						</div>
                </td>
            </tr>
            <!-- ============ FOOTER SECTION ============== -->
            <tr>
                <td id='footer' colspan="2">
                    Copyright© 2010 <a href='http://onigoetz.ch' target='_blank'>Onigoetz.ch</a> - Based on <a href='http://evolve.crazytje.be' target='_blank'>Evolve </a>
                </td>
            </tr>
        </table>
    </body>
<html>
